version: '3.8'
volumes:
  pg_data:
  static:

services:
  db:
    image: postgres
    env_file: .env
    ports:
      - "5434:5432"
    volumes:
      - pg_data://var/lib/postgresql/data

  app:
    image: berg1005/what_to_watch
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - static://opinions_app/static
    depends_on:
      - db